### ISSUE TITLE
Package hangs Emacs on Termux/Android

### ISSUE THREAD

**Issue by OverkillGuy** [akhramov/org-wild-notifier.el#22]
Recently (a few weeks ago), my phone (Lineage running Emacs via [Termux](https://termux.com/)) started hanging when loading my config. A simple `C-g` gets me out of it though.

I narrowed it down `(org-wild-notifier-mode)` . Without that statement (part of my `use-package` invocation) Emacs is fine.
Evaluating the following on Termux consistently hangs.

I haven't enough time to dig into it more.
Am assuming it's something to do with async, as it started only a few weeks ago. 
Will try to gather more info via edebug, but wanted to report on the issue first.

**Comment by akhramov** [comment]
Alright, I don't have the hardware, so a little help from your side will be appreciated.

First, let's ensure that the problem is in this package. Please run the following elisp commands and report outputs:

This command reports emacs executable filename (feel free obfuscating it, if it contains any personal info):
```
(message (file-truename (expand-file-name invocation-name invocation-directory)))
```

This one attempts to launch asynchronous GNU Emacs process. It's the very same thing org-wild-notifier does: 
```
(message "Async result is %s" (async-sandbox (lambda nil 5)))
```

The last command may either hang (which indicates that the problem is somewhere outside), or not.

If it hangs, we are going to dig a little deeper in android / termux shenanigans, like, does it handle forking / execve correctly and so on.

**Comment by OverkillGuy** [comment]
Sorry for my phrasing, I meant to say that I had no time to debug _so far_ but will have some more going forward! =)

```emacs-lisp
(message (file-truename (expand-file-name invocation-name invocation-directory)))
```
Returns  `/data/data/com.termux/files/usr/bin/emacs-26.1`, which is the Emacs package of Termux, all good so far.

```emacs-lisp
(message "Async result is %s" (async-sandbox (lambda nil 5)))
```
This hangs! Yes! Checking on the board of Termux-package for similar issues I find this:  https://github.com/termux/termux-packages/issues/1896.
Seems async has always been a problem child on Termux. Closing the issue here, I'll bump the ticket over there and disable the package when loading from Android in the meantime.

Thanks for the support and great package.

**Comment by akhramov** [comment]
That's okay, thanks for heads-up!
