### ISSUE TITLE
[Bug] Multiple values in org-wild-notifier-alert-time variable not working

### ISSUE THREAD

**Issue by ykhurshid** [akhramov/org-wild-notifier.el#39]
It would be nice to be able to set the default to alerting at various times instead of always having to set it manually via the property drawer.

For example, I'd like the default for any task to notify me 60, 30, 10, and 5 minutes prior to the deadline but it doesn't seem to work when I set the org-wild-notifier-alert-time variable to a list of numbers.

**Comment by ykhurshid** [comment]
Never mind, just realized that this is already an existing feature in the github version but it seems to not be working correctly. For example, I set this:

`        (setq org-wild-notifier-alert-time '(10 5))
`
But I only get notified 10 minutes in advance of the task, not 5 minutes.

**Comment by kresbeatz** [comment]
> Never mind, just realized that this is already an existing feature in the github version but it seems to not be working correctly. For example, I set this:
> 
> ` (setq org-wild-notifier-alert-time '(10 5))`
> But I only get notified 10 minutes in advance of the task, not 5 minutes.

Same thing for me. I just tried to simplify the task and set alert time for 1 minute (setq org-wild-notifier-alert-time '(1)) and I still got only one alert 10 minutes in advance instead of 1 minute. I tried many different combinations and can't get it to work. I'm using Doom Emacs if it matters..

**Comment by akhramov** [comment]
@kresbeatz thanks for digging into this!

@ykhurshid are you using doom, too?

**Comment by kresbeatz** [comment]
@akhramov The thing is if I directly edit ~/.emacs.d/.local/straight/build/org-wild-notifier and change 10 min alert time to 1 min it works, but of course it is not a solution. When I add (setq org-wild-notifier-alert-time '(1)) in Doom's config.el it is not working (still alerts in 10 minutes instead of 1 min). It makes me think it could be my config issue, but I tried from scratch and try all possible variants ('(1), (1), 1, '1, etc) - it won't work. However, WILD_NOTIFIER_NOTIFY_BEFORE works as it should, but of course it's not optimal. 

And another thing. Could you please add an option to alert exact at schedule or deadline time? Something like org-wild-notifier-alert-on-time with 'nil or 't options or something like that. Is it possible? Thanks!

**Comment by akhramov** [comment]
Ah, I think I got it. The problem is you don't use emacs built-in custom and the package failed to load the overridden vars in async subprocesses. #38 should resolve this.

If it's not, please re-open this ticket. Also, may I ask you to check whether the "exact alert time" feature work on the latest release?
